[package]
name = "zk-wasm"
version = "0.1.4"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ark-bn254 = "0.4"
ark-groth16 = "0.4"
ark-std = "0.4"
ark-serialize = "0.4"
ark-snark = "0.4"
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "0.1"
js-sys = "0.3"
base64 = "0.21"
num-bigint = "0.4"
regex = "1.10"

[profile.release]
opt-level = "z"
lto = true